2020-02-08 17:18:53.433330: xls/semester/Zaochniki-4-kurs-2019_2020.xlsx message: Traceback (most recent call last):
  File "/home/slavar/parser_mirea/reader.py", line 106, in run
    write_to_csv_file=write_to_csv_file, write_to_db=write_to_db)
  File "/home/slavar/parser_mirea/reader.py", line 308, in read
    column_range = get_column_range_semester(sheet, group_cell, group_name_row_num)
  File "/home/slavar/parser_mirea/reader.py", line 177, in get_column_range_semester
    day_num_val = get_day_num(day_num_col.value)
  File "/home/slavar/parser_mirea/reader.py", line 130, in get_day_num
    return days[day_name.upper()]
KeyError: '№ \nАУД.'

2020-02-08 17:19:01.921492: xls/semester/Vecherniki-4-kurs-2019_2020.xlsx message: Traceback (most recent call last):
  File "/home/slavar/parser_mirea/reader.py", line 106, in run
    write_to_csv_file=write_to_csv_file, write_to_db=write_to_db)
  File "/home/slavar/parser_mirea/reader.py", line 308, in read
    column_range = get_column_range_semester(sheet, group_cell, group_name_row_num)
  File "/home/slavar/parser_mirea/reader.py", line 177, in get_column_range_semester
    day_num_val = get_day_num(day_num_col.value)
  File "/home/slavar/parser_mirea/reader.py", line 130, in get_day_num
    return days[day_name.upper()]
KeyError: '№ \nАУД.'

2020-02-08 17:19:04.884727: xls/semester/.~lock.KBiSP-1-kurs-2-sem.xlsx# message: Traceback (most recent call last):
  File "/home/slavar/parser_mirea/reader.py", line 106, in run
    write_to_csv_file=write_to_csv_file, write_to_db=write_to_db)
  File "/home/slavar/parser_mirea/reader.py", line 280, in read
    book = xlrd.open_workbook(xlsx_parh)
  File "/home/slavar/parser_mirea/venv/lib/python3.7/site-packages/xlrd/__init__.py", line 157, in open_workbook
    ragged_rows=ragged_rows,
  File "/home/slavar/parser_mirea/venv/lib/python3.7/site-packages/xlrd/book.py", line 92, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/home/slavar/parser_mirea/venv/lib/python3.7/site-packages/xlrd/book.py", line 1278, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/home/slavar/parser_mirea/venv/lib/python3.7/site-packages/xlrd/book.py", line 1272, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b',slavar,'

